##############################
#@--------------------------@#
#|    BASIC CONFIGURATION   |#
#@--------------------------@#
##############################
# Enabled worlds and creative are self-explanatory.
# Drop-items only handles item dropping when the player is in creative mode; in survival mode items will always drop.
enabled-worlds:
    - world
creative: false
drop-items: true
auto-replant-saplings: true
damage-axe-accordingly: true
give-item-drops-directly: false
##############################
#@--------------------------@#
#|SPEED , SOUNDS & PARTICLES|#
#@--------------------------@#
##############################
# Try changing these settings if you're running on a small server.
# Log-break-speed is how many ticks it will take until
# the next set of logs will be broken. Set to 0 if you
# want the entire tree to break instantly.
#
# log-break-speed is measured in how many ticks between
# each log being broken
# 
# leaves-break-speed is measured in how many leaves are
# broken per tick.
log-break-speed: 5
leaves-break-speed: 3
leaves-breaking:
    particle: NONE
    sound: ENTITY_ITEM_PICKUP
    volume: 1
    pitch: 1
logs-breaking:
    particle: NONE
    sound: ENTITY_ITEM_PICKUP
    volume: 1
    pitch: 0.25
tree-breaking:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1