##############################
#@--------------------------@#
#|    BASIC CONFIGURATION   |#
#@--------------------------@#
##############################
# Enabled worlds and creative are self-explanatory.
# Drop-items only handles item dropping when the player is in creative mode; in survival mode items will always drop.
enabled-worlds:
    - world
creative: false
drop-items: true
auto-replant-saplings: true
damage-axe-accordingly: true
give-item-drops-directly: false

##############################
#@--------------------------@#
#|     FORBIDDEN BLOCKS     |#
#@--------------------------@#
##############################
#  This is a list of blocks that the plugin will check for to
#  make sure that only naturally generated trees are being broken,
#  and not player created structures.
#  If these blocks are placed adjacent to a tree's trunk or leaves,
#  the plugin will not cut it down.
forbidden-blocks:
    - CHEST
    - WALL_TORCH
    - REDSTONE_WALL_TORCH
    - REDSTONE_TORCH
    - OAK_SIGN
    - BIRCH_SIGN
    - SPRUCE_SIGN
    - JUNGLE_SIGN
    - ACACIA_SIGN
    - DARK_OAK_SIGN
    - COBBLESTONE
    - STONE_BRICKS
    - OAK_PLANKS
    - BIRCH_PLANKS
    - SPRUCE_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - DARK_OAK_WALL_SIGN
    - OAK_WALL_SIGN
    - BIRCH_WALL_SIGN
    - SPRUCE_WALL_SIGN
    - JUNGLE_WALL_SIGN
    - ACACIA_WALL_SIGN
    - GLOWSTONE
    - REDSTONE_LAMP
    - DAYLIGHT_DETECTOR
    - LADDER
    - FURNACE
    - BLAST_FURNACE
##############################
#@--------------------------@#
#|SPEED , SOUNDS & PARTICLES|#
#@--------------------------@#
##############################
# Try changing these settings if you're running on a small server.
# Log-break-speed is how many ticks it will take until
# the next set of logs will be broken. Set to 0 if you
# want the entire tree to break instantly.
#
# log-break-speed is measured in how many ticks between
# each log being broken
# 
# leaves-break-speed is measured in how many leaves are
# broken per tick.
leaves-breaking:
    speed: 3
    particle: NONE
    sound: ENTITY_ITEM_PICKUP
    volume: 1
    pitch: 1
logs-breaking:
    speed: 5
    particle: NONE
    sound: ENTITY_ITEM_PICKUP
    volume: 1
    pitch: 0.25
tree-breaking:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1