# ---------------------------------------
#          IGNORE THIS YAML FILE
# * This file is for the developer
# * No configuration here
# ---------------------------------------
name: TreeClick
main: me.gelloe.TreeClick.Main
version: 1.5.0
author: gelloe
api-version: 1.13
commands:
    treeclick:
        description: 
        usage: /<command> [update | help]
        aliases: [tc]
        permission: treeclick